from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 386)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame2 = QtWidgets.QVBoxLayout()
        self.frame2.setObjectName("frame2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(200, 20))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.frame2.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(50, 15))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_7.addWidget(self.lcdNumber)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(50, 15))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lcdNumber_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_10.addWidget(self.lcdNumber_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMinimumSize(QtCore.QSize(50, 15))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lcdNumber_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.verticalLayout_11.addWidget(self.lcdNumber_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(50, 15))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lcdNumber_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.verticalLayout_12.addWidget(self.lcdNumber_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setMinimumSize(QtCore.QSize(50, 15))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lcdNumber_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.verticalLayout_9.addWidget(self.lcdNumber_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.frame2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.frame2, 0, 1, 1, 1)
        self.frame3 = QtWidgets.QVBoxLayout()
        self.frame3.setObjectName("frame3")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setMinimumSize(QtCore.QSize(200, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.frame3.addWidget(self.label_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setMinimumSize(QtCore.QSize(100, 15))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_17.addWidget(self.label_15)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sliderFan1 = QtWidgets.QSlider(Form)
        self.sliderFan1.setMinimumSize(QtCore.QSize(0, 30))
        self.sliderFan1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sliderFan1.setMaximum(3)
        self.sliderFan1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFan1.setObjectName("sliderFan1")
        self.horizontalLayout_10.addWidget(self.sliderFan1)
        self.labelFanSpeed1 = QtWidgets.QLabel(Form)
        self.labelFanSpeed1.setMinimumSize(QtCore.QSize(15, 0))
        self.labelFanSpeed1.setMaximumSize(QtCore.QSize(15, 16777215))
        self.labelFanSpeed1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFanSpeed1.setObjectName("labelFanSpeed1")
        self.horizontalLayout_10.addWidget(self.labelFanSpeed1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_17)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setMinimumSize(QtCore.QSize(100, 15))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_19.addWidget(self.label_16)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sliderFan2 = QtWidgets.QSlider(Form)
        self.sliderFan2.setMinimumSize(QtCore.QSize(0, 30))
        self.sliderFan2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sliderFan2.setMaximum(3)
        self.sliderFan2.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFan2.setObjectName("sliderFan2")
        self.horizontalLayout_11.addWidget(self.sliderFan2)
        self.labelFanSpeed2 = QtWidgets.QLabel(Form)
        self.labelFanSpeed2.setMinimumSize(QtCore.QSize(15, 0))
        self.labelFanSpeed2.setMaximumSize(QtCore.QSize(15, 16777215))
        self.labelFanSpeed2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFanSpeed2.setObjectName("labelFanSpeed2")
        self.horizontalLayout_11.addWidget(self.labelFanSpeed2)
        self.verticalLayout_19.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6.addLayout(self.verticalLayout_19)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.frame3.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.frame3, 1, 0, 1, 1)
        self.frame1 = QtWidgets.QVBoxLayout()
        self.frame1.setObjectName("frame1")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(200, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame1.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxAutoWork = QtWidgets.QCheckBox(Form)
        self.checkBoxAutoWork.setObjectName("checkBoxAutoWork")
        self.horizontalLayout_3.addWidget(self.checkBoxAutoWork)
        self.checkBoxOffLock = QtWidgets.QCheckBox(Form)
        self.checkBoxOffLock.setObjectName("checkBoxOffLock")
        self.horizontalLayout_3.addWidget(self.checkBoxOffLock)
        self.frame1.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(120, 15))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.spinBoxPeriod = QtWidgets.QSpinBox(Form)
        self.spinBoxPeriod.setMaximum(10000)
        self.spinBoxPeriod.setObjectName("spinBoxPeriod")
        self.verticalLayout_2.addWidget(self.spinBoxPeriod)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(120, 15))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.spinBoxTime = QtWidgets.QSpinBox(Form)
        self.spinBoxTime.setMaximum(10000)
        self.spinBoxTime.setObjectName("spinBoxTime")
        self.verticalLayout_3.addWidget(self.spinBoxTime)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(120, 15))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.spinBoxLimit = QtWidgets.QSpinBox(Form)
        self.spinBoxLimit.setMaximum(10000)
        self.spinBoxLimit.setObjectName("spinBoxLimit")
        self.verticalLayout_4.addWidget(self.spinBoxLimit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.frame1.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.frame1, 0, 0, 1, 1)
        self.frame5 = QtWidgets.QVBoxLayout()
        self.frame5.setObjectName("frame5")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setMinimumSize(QtCore.QSize(200, 20))
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.frame5.addWidget(self.label_17)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBoxTamburLight = QtWidgets.QCheckBox(Form)
        self.checkBoxTamburLight.setObjectName("checkBoxTamburLight")
        self.horizontalLayout_7.addWidget(self.checkBoxTamburLight)
        self.checkBoxRoomLight = QtWidgets.QCheckBox(Form)
        self.checkBoxRoomLight.setObjectName("checkBoxRoomLight")
        self.horizontalLayout_7.addWidget(self.checkBoxRoomLight)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.frame5.addLayout(self.horizontalLayout_7)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setMinimumSize(QtCore.QSize(200, 15))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.frame5.addWidget(self.label_18)
        self.comboBoxLight = QtWidgets.QComboBox(Form)
        self.comboBoxLight.setObjectName("comboBoxLight")
        self.comboBoxLight.addItem("")
        self.comboBoxLight.addItem("")
        self.comboBoxLight.addItem("")
        self.frame5.addWidget(self.comboBoxLight)
        self.gridLayout.addLayout(self.frame5, 2, 0, 1, 1)
        self.frame6 = QtWidgets.QVBoxLayout()
        self.frame6.setObjectName("frame6")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setMinimumSize(QtCore.QSize(200, 20))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.frame6.addWidget(self.label_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBoxLockTambur = QtWidgets.QCheckBox(Form)
        self.checkBoxLockTambur.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLockTambur.setTristate(False)
        self.checkBoxLockTambur.setObjectName("checkBoxLockTambur")
        self.horizontalLayout_8.addWidget(self.checkBoxLockTambur)
        self.checkBoxLockRoom = QtWidgets.QCheckBox(Form)
        self.checkBoxLockRoom.setObjectName("checkBoxLockRoom")
        self.horizontalLayout_8.addWidget(self.checkBoxLockRoom)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 1)
        self.frame6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setMinimumSize(QtCore.QSize(100, 20))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setMinimumSize(QtCore.QSize(100, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_9.addWidget(self.label_21)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.frame6.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.frame6, 2, 1, 1, 1)
        self.frame4 = QtWidgets.QVBoxLayout()
        self.frame4.setObjectName("frame4")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(200, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.frame4.addWidget(self.label_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setMinimumSize(QtCore.QSize(100, 15))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_14.addWidget(self.label_12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sliderShutter1 = QtWidgets.QSlider(Form)
        self.sliderShutter1.setMinimumSize(QtCore.QSize(0, 30))
        self.sliderShutter1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sliderShutter1.setMaximum(1000)
        self.sliderShutter1.setOrientation(QtCore.Qt.Horizontal)
        self.sliderShutter1.setObjectName("sliderShutter1")
        self.horizontalLayout_12.addWidget(self.sliderShutter1)
        self.labelShutterPos1 = QtWidgets.QLabel(Form)
        self.labelShutterPos1.setMinimumSize(QtCore.QSize(30, 0))
        self.labelShutterPos1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.labelShutterPos1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelShutterPos1.setObjectName("labelShutterPos1")
        self.horizontalLayout_12.addWidget(self.labelShutterPos1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setMinimumSize(QtCore.QSize(100, 15))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.sliderShutter2 = QtWidgets.QSlider(Form)
        self.sliderShutter2.setMinimumSize(QtCore.QSize(0, 30))
        self.sliderShutter2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sliderShutter2.setMaximum(1000)
        self.sliderShutter2.setOrientation(QtCore.Qt.Horizontal)
        self.sliderShutter2.setObjectName("sliderShutter2")
        self.horizontalLayout_13.addWidget(self.sliderShutter2)
        self.labelShutterPos2 = QtWidgets.QLabel(Form)
        self.labelShutterPos2.setMinimumSize(QtCore.QSize(30, 0))
        self.labelShutterPos2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.labelShutterPos2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelShutterPos2.setObjectName("labelShutterPos2")
        self.horizontalLayout_13.addWidget(self.labelShutterPos2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.frame4.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.frame4, 1, 1, 1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout)
        self.applyButton = QtWidgets.QPushButton(Form)
        self.applyButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout_21.addWidget(self.applyButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tools"))
        self.label_5.setText(_translate("Form", "Датчики концентрации"))
        self.label_6.setText(_translate("Form", "№1"))
        self.label_7.setText(_translate("Form", "№2"))
        self.label_8.setText(_translate("Form", "№3"))
        self.label_9.setText(_translate("Form", "№4"))
        self.label_10.setText(_translate("Form", "Среднее"))
        self.label_14.setText(_translate("Form", "Управление вентиляторами"))
        self.label_15.setText(_translate("Form", "Скорость вентилятора №1"))
        self.labelFanSpeed1.setText(_translate("Form", "0"))
        self.label_16.setText(_translate("Form", "Скорость вентилятора №2"))
        self.labelFanSpeed2.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "Управление клапаном хлора"))
        self.checkBoxAutoWork.setText(_translate("Form", "Автоуправление клапаном"))
        self.checkBoxOffLock.setText(_translate("Form", "Отключить блокировку"))
        self.label_2.setText(_translate("Form", "Период включения"))
        self.label_3.setText(_translate("Form", "Время включения"))
        self.label_4.setText(_translate("Form", "Порог"))
        self.label_17.setText(_translate("Form", "Управление освещением"))
        self.checkBoxTamburLight.setText(_translate("Form", "Освещение тамбура"))
        self.checkBoxRoomLight.setText(_translate("Form", "Освещение камеры"))
        self.label_18.setText(_translate("Form", "Световое табло"))
        self.comboBoxLight.setItemText(0, _translate("Form", "Выключено"))
        self.comboBoxLight.setItemText(1, _translate("Form", "Включено"))
        self.comboBoxLight.setItemText(2, _translate("Form", "Мигание"))
        self.label_19.setText(_translate("Form", "Управление электрозамками"))
        self.checkBoxLockTambur.setText(_translate("Form", "Замок тамбура"))
        self.checkBoxLockRoom.setText(_translate("Form", "Замок камеры"))
        self.label_20.setText(_translate("Form", "тамбур"))
        self.label_21.setText(_translate("Form", "камера"))
        self.label_11.setText(_translate("Form", "Управление воздушными заслонками"))
        self.label_12.setText(_translate("Form", "Положение заслонки №1"))
        self.labelShutterPos1.setText(_translate("Form", "0"))
        self.label_13.setText(_translate("Form", "Положение заслонки №2"))
        self.labelShutterPos2.setText(_translate("Form", "0"))
        self.applyButton.setText(_translate("Form", "Применить"))
