from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 113)
        Form.setMinimumSize(QtCore.QSize(0, 113))
        Form.setMaximumSize(QtCore.QSize(999999, 113))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(100, 20))
        self.label.setMaximumSize(QtCore.QSize(999999, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lcd_timer = QtWidgets.QLCDNumber(Form)
        self.lcd_timer.setMinimumSize(QtCore.QSize(300, 30))
        self.lcd_timer.setMaximumSize(QtCore.QSize(9999999, 30))
        self.lcd_timer.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_timer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcd_timer.setDigitCount(8)
        self.lcd_timer.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd_timer.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_timer.setProperty("value", 0.0)
        self.lcd_timer.setObjectName("lcd_timer")
        self.verticalLayout.addWidget(self.lcd_timer)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setMinimumSize(QtCore.QSize(0, 45))
        self.reset_button.setMaximumSize(QtCore.QSize(125, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.stop_button = QtWidgets.QPushButton(Form)
        self.stop_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 45))
        self.stop_button.setMaximumSize(QtCore.QSize(125, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.stop_button.setFont(font)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.start_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setMinimumSize(QtCore.QSize(0, 45))
        self.start_button.setMaximumSize(QtCore.QSize(125, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.start_button.setFont(font)
        self.start_button.setStyleSheet("")
        self.start_button.setDefault(False)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Таймер"))
        self.reset_button.setText(_translate("Form", "Сброс"))
        self.stop_button.setText(_translate("Form", "Стоп"))
        self.start_button.setText(_translate("Form", "Старт"))
